#!/bin/bash
# System Monitoring Script
# Generated by GAA-4.0 on $(date)

echo "=== GAA-4.0 System Health Monitor ==="
echo "Report Generated: $(date)"
echo "Execution Path: ${EXECUTION_PATH:-./data}"
echo ""

echo "--- 1. Disk Usage ---"
df -h "${EXECUTION_PATH:-./data}" | head -n 1
df -h "${EXECUTION_PATH:-./data}" | tail -n 1
echo ""

echo "--- 2. Data Directory Overview ---"
echo "Total files: $(ls -1 "${EXECUTION_PATH:-./data}" 2>/dev/null | wc -l)"
echo "Reports (.md): $(find "${EXECUTION_PATH:-./data}/reports" -name "*.md" 2>/dev/null | wc -l)"
echo "Tools (.sh): $(find "${EXECUTION_PATH:-./data}/tools" -name "*.sh" 2>/dev/null | wc -l)"
echo "Knowledge Base (.md): $(find "${EXECUTION_PATH:-./data}/knowledge" -name "*.md" 2>/dev/null | wc -l)"
echo ""

echo "--- 3. Recent File Modifications (Last 5) ---"
ls -lt "${EXECUTION_PATH:-./data}" 2>/dev/null | head -n 6
echo ""

echo "--- 4. Execution Policy Snapshot ---"
if [ -f exec_policy.json ]; then
    echo "Policy file found. Network access: $(grep -q 'allow_net.*true' exec_policy.json && echo 'Enabled' || echo 'Disabled')"
else
    echo "exec_policy.json not found."
fi
echo ""

echo "--- 5. System Messages (Placeholder) ---"
echo "No critical system messages detected (based on available log files)."
echo "Log files in data/: $(find "${EXECUTION_PATH:-./data}" -name "*.log" 2>/dev/null | wc -l)"

echo "=== Monitor Complete ==="
